# setup Python 3.11 environment
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

# bypass pep 668
[phases.install]
cmds = [
    "pip install --break-system-packages --upgrade pip",
    "pip install --break-system-packages -r requirements.txt"
]

# build confirmation
[phases.build]
cmds = ["echo 'Build phase complete'"]

# start the flask with gunicorn
[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1"
